apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-database
spec:
  ports:
  - port: 5432
  selector:
    app: database
  clusterIP: None # Headless service cho StatefulSet