apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: frontend
    