apiVersion: v1
kind: Secret
metadata:
  # Tên của Secret, ví dụ: my-final-project-secret
  name: {{ .Release.Name }}-secret

  # --- KHỐI ĐƯỢC THÊM VÀO ĐỂ SỬA LỖI ---
  annotations:
    # Chỉ thị cho Helm chạy tài nguyên này trước khi cài đặt/nâng cấp
    "helm.sh/hook": pre-install,pre-upgrade
    
    # Gán độ ưu tiên. Số nhỏ hơn chạy trước.
    "helm.sh/hook-weight": "-5"

    # Chính sách xóa: Xóa hook cũ trước khi tạo hook mới khi nâng cấp
    "helm.sh/hook-delete-policy": before-hook-creation
  # --- KẾT THÚC KHỐI THÊM VÀO ---

type: Opaque
stringData:
  # Mật khẩu database. Helm sẽ lấy giá trị từ file values.yaml
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}